name:  Netikslumas skaidrėse
description: Pranešimas apie netikslumą skaidrėse.
title: "P__-_ (v1.0) sk._: netikslumas → taisymas (esmė)"
labels: ["Naujas :new:", "Vieta: skaidrės :orange_book:"]
body:
  - type: markdown
    attributes:
      value: |
          Temos **pavadinime** apibūdinkite netikslumo esmę, kuri padėtų **kitiems** skaitytojams **greitai susiorientuoti**, kad apie šį netikslumą jau pranešta.

          1. Prašykite skaidrių bloko kodą (pvz., `P01-4`);  
          2. Bloko versiją, pvz., (`v1.0`). Jei versija neparašyta, tai ji yra `1.0`;  
          3. Skaidrės numerį, pvz. `sk.14`, per kablelį gali būti nurodytos kelios skaidrės, pvz., `sk.1,5`;  
          4. Apibūdinkite netikslumo esmę. Jei galima, tokiu formatu: `netikslumas → taisymas (esmė)`.
          Pvz.:  
          „`P01-4 (v1.0) sk.14: kopppiuteris → kompiuteris (rašyba)`“  
          „`P11-1 (v2.1) sk.1,5: praleistas žodis "tačiau"`“
  - type: textarea
    id: screenshot
    attributes:
      label: Ekrano nuotrauka su pažymėtais netikslumais
      description: Viena ar kelios ekrano nuotraukos („Screenshot“) su pažymėtomis netikslumų vietomis.
    validations:
      required: true
  - type: dropdown
    id: error-type
    attributes:
      label: Netikslumo tipas
      description: Pasirinkite vieną ar kelis.
      multiple: true
      options:
        - rašyba (praleista raidė ar kt.)
        - gramatika (nesuderinti linksniai ar kt.)
        - praleistas žodis 
        - pasikartojimas (pasikartojantis žodis ar frazė)
        - skaičiavimo klaida
        - numeracijos klaida
        - fakto klaida
        - netinkamas terminas
        - skyryba
        - stilius
        - kita
    validations:
      required: true
  - type: input
    id: error-with-context
    attributes:
      label: Netikslumo tekstas su keliais žodžiais aplinkui
      description: To reikia greitai paieškai dokumente.
  - type: input
    id: error
    attributes:
      label: Netikslumo tekstas
  - type: input
    id: correction
    attributes:
      label: Siūlomas taisymo tekstas
  - type: textarea
    id: comment
    attributes:
      label: Komentaras
      description: Jei reikia, pateikite papildomos informacijos.
  - type: dropdown
    id: course
    attributes:
      label: Dalykas
      options:
        - BS-2024
        - kitas
      default: 0
  - type: dropdown
    id: place
    attributes:
      label: Netikslumo vieta
      options:
        - skaidrės
        - kitur
      default: 0
  - type: checkboxes
    id: terms
    attributes:
      label: Patvirtinimas
      options:
        - label: Temos pavadinime nurodžiau skaidrių bloko kodą, versiją ir skaidrės numerį.
          required: true
        - label: Temos pavadinime nurodžiau konkrečios problemos esmę.
          required: true
        - label: "Apie šią problemą dar niekas nėra pranešęs: esu pirmasis/pirmoji."
